# Generated by Django 5.0 on 2024-08-27 14:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user_environment', '0003_review'),
    ]

    operations = [
        migrations.RenameField(
            model_name='review',
            old_name='_description',
            new_name='details',
        ),
        migrations.RenameField(
            model_name='review',
            old_name='_rating',
            new_name='rating',
        ),
        migrations.RenameField(
            model_name='review',
            old_name='_time_created',
            new_name='time_created',
        ),
        migrations.RenameField(
            model_name='review',
            old_name='_title',
            new_name='title_review',
        ),
    ]
